vinculacion('Alejandro','TCO').
vinculacion('Pedro','HC').
vinculacion('Juan','HCH').
vinculacion('Miguel','MTO').
vinculacion('Ana','Planta').
vinculacion('Marcos','TCO').
vinculacion('David','HC').
vinculacion('Felipe','HCH').
vinculacion('Andres','MTO').
vinculacion('Jose','Planta').
vinculacion('Jesus','TCO').
vinculacion('Tatiana','HC').
vinculacion('Rocio','HCH').
vinculacion('Carlos','MTO').
vinculacion('Fernanda','Planta').
vinculacion('Jhon','TCO').
vinculacion('Ernesto','HC').
vinculacion('Pilar','HCH').
vinculacion('Helena','MTO').
vinculacion('Jaime','Planta').
vinculacion('Nicolas','TCO').
vinculacion('Oscar','HC').
vinculacion('Camilo','HCH').
vinculacion('Sandra','MTO').
vinculacion('Andrea','Planta').

horas_Contrato('TCO',40).
horas_Contrato('HC',16).
horas_Contrato('HCH',16).
horas_Contrato('MTO',20).
horas_Contrato('Planta',40).

contrato_Categoria_Valorhora('TCO','Asistente',10000).
contrato_Categoria_Valorhora('MTO','Asistente',9000).
contrato_Categoria_Valorhora('HC','Asistente',8000).
contrato_Categoria_Valorhora('HCH','Asistente',8000).
contrato_Categoria_Valorhora('Planta','Asistente',20000).
contrato_Categoria_Valorhora('TCO','Titular',50000).
contrato_Categoria_Valorhora('MTO','Titular',40000).
contrato_Categoria_Valorhora('HC','Titular',30000).
contrato_Categoria_Valorhora('HCH','Titular',30000).
contrato_Categoria_Valorhora('Planta','Titular',100000).

categoria('Alejandro','Asistente').
categoria('Pedro','Asistente').
categoria('Juan','Titular').
categoria('Miguel','Asistente').
categoria('Ana','Titular').
categoria('Marcos','Asistente').
categoria('David','Titular').
categoria('Felipe','Asistente').
categoria('Andres','Titular').
categoria('Jose','Asistente').
categoria('Jesus','Titular'). 
categoria('Tatiana','Asistente').
categoria('Rocio','Titular').
categoria('Carlos','Asistente').
categoria('Fernanda','Titular').
categoria('Jhon','Asistente').
categoria('Ernesto','Titular').
categoria('Pilar','Asistente').
categoria('Helena','Titular').
categoria('Jaime','Asistente').
categoria('Nicolas','Titular').
categoria('Oscar','Asistente').
categoria('Camilo','Titular').
categoria('Sandra','Asistente').
categoria('Andrea','Titular').

adicional_Contrato('TCO',15).
adicional_Contrato('MTO',12).
adicional_Contrato('HC',10).
adicional_Contrato('HCH',0).
adicional_Contrato('Planta',25).

tipo_Semestre(18,'Normal').
tipo_Semestre(4,'Vacacional').

sueldo(X) :- categoria(X,C), vinculacion(X,Y),  horas_contrato(Y,Z), contrato_Categoria_Valorhora(Y,C,(Z*).
